const {
  WAYFARER_NODE_ENV,
  WAYFARER_DEV_PORT,
  WAYFARER_DEV_DATABASE_URL,
  WAYFARER_DEV_MAIL_USERNAME,
  WAYFARER_DEV_MAIL_PASSWORD,
  WAYFARER_DEV_OAUTH_CLIENTID,
  WAYFARER_DEV_OAUTH_CLIENT_SECRET,
  WAYFARER_DEV_OAUTH_REFRESH_TOKEN,
  WAYFARER_DEV_BCRYPT_SALT_ROUNDS,
  WAYFARER_DEV_JWT_SECRET_KEY
} = process.env;

export default {
  WAYFARER_NODE_ENV,
  WAYFARER_PORT: WAYFARER_DEV_PORT,
  WAYFARER_DATABASE_URL: WAYFARER_DEV_DATABASE_URL,
  WAYFARER_MAIL_USERNAME: WAYFARER_DEV_MAIL_USERNAME,
  WAYFARER_MAIL_PASSWORD: WAYFARER_DEV_MAIL_PASSWORD,
  WAYFARER_OAUTH_CLIENTID: WAYFARER_DEV_OAUTH_CLIENTID,
  WAYFARER_OAUTH_CLIENT_SECRET: WAYFARER_DEV_OAUTH_CLIENT_SECRET,
  WAYFARER_OAUTH_REFRESH_TOKEN: WAYFARER_DEV_OAUTH_REFRESH_TOKEN,
  WAYFARER_BCRYPT_SALT_ROUNDS: WAYFARER_DEV_BCRYPT_SALT_ROUNDS,
  WAYFARER_JWT_SECRET_KEY: WAYFARER_DEV_JWT_SECRET_KEY
};
