const {
  WAYFARER_NODE_ENV,
  WAYFARER_DEV_PORT,
  WAYFARER_DEV_DATABASE_URL
} = process.env;

export default {
  WAYFARER_NODE_ENV,
  WAYFARER_PORT: WAYFARER_DEV_PORT,
  WAYFARER_DATABASE_URL: WAYFARER_DEV_DATABASE_URL
};
