const {
  WAYFARER_NODE_ENV,
  WAYFARER_PROD_PORT,
  WAYFARER_PROD_DATABASE_URL
} = process.env;
  
export default {
  WAYFARER_NODE_ENV,
  WAYFARER_PORT: WAYFARER_PROD_PORT,
  WAYFARER_DATABASE_URL: WAYFARER_PROD_DATABASE_URL
};
