const {
  WAYFARER_NODE_ENV,
  WAYFARER_PROD_PORT,
  WAYFARER_PROD_DATABASE_URL,
  WAYFARER_PROD_MAIL_USERNAME,
  WAYFARER_PROD_MAIL_PASSWORD,
  WAYFARER_PROD_OAUTH_CLIENTID,
  WAYFARER_PROD_OAUTH_CLIENT_SECRET,
  WAYFARER_PROD_OAUTH_REFRESH_TOKEN,
  WAYFARER_PROD_BCRYPT_SALT_ROUNDS,
  WAYFARER_PROD_JWT_SECRET_KEY

} = process.env;
  
export default {
  WAYFARER_NODE_ENV,
  WAYFARER_PORT: WAYFARER_PROD_PORT,
  WAYFARER_DATABASE_URL: WAYFARER_PROD_DATABASE_URL,
  WAYFARER_MAIL_USERNAME: WAYFARER_PROD_MAIL_USERNAME,
  WAYFARER_MAIL_PASSWORD: WAYFARER_PROD_MAIL_PASSWORD, 
  WAYFARER_OAUTH_CLIENTID: WAYFARER_PROD_OAUTH_CLIENTID,
  WAYFARER_OAUTH_CLIENT_SECRET: WAYFARER_PROD_OAUTH_CLIENT_SECRET,
  WAYFARER_OAUTH_REFRESH_TOKEN: WAYFARER_PROD_OAUTH_REFRESH_TOKEN,
  WAYFARER_BCRYPT_SALT_ROUNDS: WAYFARER_PROD_BCRYPT_SALT_ROUNDS,
  WAYFARER_JWT_SECRET_KEY: WAYFARER_PROD_JWT_SECRET_KEY
};
