const {
  WAYFARER_NODE_ENV,
  WAYFARER_TEST_PORT ,
  WAYFARER_TEST_DATABASE_URL
} = process.env;
  
export default {
  WAYFARER_NODE_ENV,
  WAYFARER_PORT: WAYFARER_TEST_PORT,
  WAYFARER_DATABASE_URL: WAYFARER_TEST_DATABASE_URL
};
  
