const {
  WAYFARER_NODE_ENV,
  WAYFARER_TEST_PORT ,
  WAYFARER_TEST_DATABASE_URL,
  WAYFARER_TEST_MAIL_USERNAME,
  WAYFARER_TEST_MAIL_PASSWORD,
  WAYFARER_TEST_OAUTH_CLIENTID,
  WAYFARER_TEST_OAUTH_CLIENT_SECRET,
  WAYFARER_TEST_OAUTH_REFRESH_TOKEN,
  WAYFARER_TEST_BCRYPT_SALT_ROUNDS
} = process.env;
  
export default {
  WAYFARER_NODE_ENV,
  WAYFARER_PORT: WAYFARER_TEST_PORT,
  WAYFARER_DATABASE_URL: WAYFARER_TEST_DATABASE_URL,
  WAYFARER_MAIL_USERNAME: WAYFARER_TEST_MAIL_USERNAME,
  WAYFARER_MAIL_PASSWORD: WAYFARER_TEST_MAIL_PASSWORD,
  WAYFARER_OAUTH_CLIENTID: WAYFARER_TEST_OAUTH_CLIENTID,
  WAYFARER_OAUTH_CLIENT_SECRET: WAYFARER_TEST_OAUTH_CLIENT_SECRET,
  WAYFARER_OAUTH_REFRESH_TOKEN: WAYFARER_TEST_OAUTH_REFRESH_TOKEN,
  WAYFARER_BCRYPT_SALT_ROUNDS: WAYFARER_TEST_BCRYPT_SALT_ROUNDS
};
  
